variables:
    IMAGE_NAME: detunj/demo-app
    IMAGE_TAG: python-app-1.0

stages:
  - test
  - build
  - deploy

run_tests:
    stage: test
    image: python:3.9-slim-buster
    before_script:
        - apt-get update && apt-get install make
    script:
        - make test

build_image:
    stage: build
    image: docker:24.0.2
    services:
        - docker:24.0.2-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
    stage: deploy
    before_script:
        - chmod 400 $SSH_KEY
    script:
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@ec2-65-0-94-77.ap-south-1.compute.amazonaws.com "
            echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin &&
            docker ps -aq | xargs docker stop | xargs docker rm &&
            docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"

