variables:
    IMAGE_NAME: detunj/demo-app
    IMAGE_TAG: python-app-1.0

run tests:
    image: python:3.9-slim-buster
    before_script:
        - apt-get update && apt-get install make
    script:
        - make test

build_image:
    image: docker:24.0.2
    services:
        - docker:24.0.2-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG